DROP DATABASE IF EXISTS heroku_2e1a4b9d7fea309;

CREATE DATABASE heroku_2e1a4b9d7fea309;

USE heroku_2e1a4b9d7fea309;

CREATE TABLE burgers (
  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(30) NOT NULL, 
  devoured BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
);